CREATE TABLE `ah_building_detail` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
 `is_delete` tinyint(1) NOT NULL DEFAULT '1' COMMENT '时效;0=失效,1=有效;默认1;',
 `is_stop` tinyint(1) NOT NULL DEFAULT '1' COMMENT '开盘;2=封盘,1=开盘;默认1;',
 `is_passed` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态;1=未审核,2=已审核,3=未通过;默认1;',
 `building_base_id` bigint(20) NOT NULL COMMENT '楼盘表ID',
 `title` varchar(255) NOT NULL COMMENT '楼盘标题',
 `total_building` varchar(255) NOT NULL COMMENT '总栋数',
 `total_house` varchar(255) NOT NULL COMMENT '总套数',
 `description` varchar(255) NOT NULL COMMENT '详细描述',
 `url` varchar(255) NOT NULL COMMENT '封面宣传',
 `address` varchar(255) NOT NULL COMMENT '楼盘地址',
 `area_size` varchar(255) NOT NULL COMMENT '占地面积',
 `build_size` varchar(255) NOT NULL COMMENT '建筑面积',
 `volume_rate` varchar(255) NOT NULL COMMENT '容积率',
 `green_rate` varchar(255) NOT NULL COMMENT '绿化率',
 `around` varchar(255) NOT NULL COMMENT '周边环境',
 `traffic` varchar(255) NOT NULL COMMENT '交通状况',
 `developer` varchar(255) NOT NULL COMMENT '开发商',
 `park_space` varchar(255) NOT NULL COMMENT '停车位',
 `property_fee` int(11) NOT NULL COMMENT '物业费',
 `property_company` varchar(255) NOT NULL COMMENT '物业公司',
 `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '装修状况;1=毛胚,2=精装修,3=现房期房,4=现房;默认1;',
 `floor` tinyint(2) NOT NULL DEFAULT '1' COMMENT '楼层状况;1=中,2=高,3=低;默认1;',
 `sale_license` varchar(255) NOT NULL COMMENT '预售证号',
 `average_price` varchar(255) NOT NULL COMMENT '均价',
 `years` varchar(255) NOT NULL COMMENT '建筑年代',
 `province` varchar(255) NOT NULL COMMENT '省份',
 `city` varchar(255) NOT NULL COMMENT '城市',
 `county` varchar(255) NOT NULL COMMENT '地区',
 `open_price` varchar(255) NOT NULL COMMENT '开盘价',
 `opened_at` datetime NOT NULL COMMENT '开盘日期',
 `live_in_at` datetime NOT NULL COMMENT '入住时间',
 `created_at` datetime NOT NULL COMMENT '创建时间',
 `updated_at` datetime NOT NULL COMMENT '修改时间',
 PRIMARY KEY (`id`),
 KEY `building_base_id` (`building_base_id`),
 CONSTRAINT `ah_building_detail_ibfk_1` FOREIGN KEY (`building_base_id`) REFERENCES `ah_building_base` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='楼盘详情表';

CREATE TABLE `ah_images` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
 `is_delete` tinyint(1) NOT NULL DEFAULT '1' COMMENT '时效;0=失效,1=有效;默认1;',
 `back_user_id` bigint(20) NOT NULL COMMENT '后台业务员表ID',
 `target_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '类型;1=楼盘,2=新房,3=二手房;默认1;',
 `target_id` bigint(20) NOT NULL COMMENT '目标表ID',
 `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '类型;1=外景图,2=周边配套图,3=户型图,4=卧室图,5=厨房,6=卫生间,7=阳台,8=其他;默认1;',
 `title` varchar(255) NOT NULL COMMENT '图片标题',
 `icon` varchar(255) NOT NULL COMMENT '小图地址',
 `url` varchar(255) NOT NULL COMMENT '大图地址',
 `created_at` datetime NOT NULL COMMENT '创建时间',
 `updated_at` datetime NOT NULL COMMENT '修改时间',
 PRIMARY KEY (`id`),
 KEY `back_user_id` (`back_user_id`),
 CONSTRAINT `ah_images_ibfk_1` FOREIGN KEY (`back_user_id`) REFERENCES `ah_back_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='图片表';

CREATE TABLE `ah_house` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `is_delete` tinyint(1) NOT NULL DEFAULT '1' COMMENT '时效;0=失效,1=有效;默认1;',
  `is_passed` tinyint(1) NOT NULL DEFAULT '1' COMMENT '审核;1=未审核,2=已审核,3=未通过;默认1;',
  `on_sales` tinyint(1) NOT NULL DEFAULT '1' COMMENT '销售;1=在售,2=已售,3=待售,4=正售;默认1;',
  `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '类型;1=新房,2=二手房;默认1;',
  `building_base_id` bigint(20) NULL DEFAULT NULL COMMENT '楼盘表ID',
  `back_user_id` bigint(20) NULL DEFAULT NULL COMMENT '业务员表ID',
  `suite_name` varchar(255) NULL DEFAULT NULL COMMENT '小区名称',
  `namePinyin` varchar(255) NOT NULL COMMENT '小区名称拼音',
  `pinyin` varchar(255) NOT NULL COMMENT '小区拼音首字母',
  `title` varchar(255) NOT NULL COMMENT '房子标题',
  `code` varchar(255) NOT NULL COMMENT '房源编号',
  `description` varchar(255) NOT NULL COMMENT '详细描述',
  `url` varchar(255) NOT NULL COMMENT '封面宣传',
  `address` varchar(255) NOT NULL COMMENT '地址',
  `area_size` varchar(255) NOT NULL COMMENT '面积',
  `price` varchar(255) NOT NULL COMMENT '售价',
  `around` varchar(255) NOT NULL COMMENT '周边环境',
  `traffic` varchar(255) NOT NULL COMMENT '交通状况',
  `property` int(11) NOT NULL COMMENT '产权',
  `property_fee` int(11) NOT NULL COMMENT '物业费',
  `property_company` varchar(255) NOT NULL COMMENT '物业公司',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '装修状况;1=毛胚,2=精装修,3=现房期房,4=现房;默认1;',
  `floor` tinyint(2) NOT NULL DEFAULT '1' COMMENT '楼层状况;1=中,2=高,3=低;默认1;',
  `room` tinyint(2) NOT NULL DEFAULT '1' COMMENT '室',
  `hall` tinyint(2) NOT NULL DEFAULT '1' COMMENT '厅',
  `province` varchar(255) NOT NULL COMMENT '省份',
  `city` varchar(255) NOT NULL COMMENT '城市',
  `county` varchar(255) NOT NULL COMMENT '地区',
  `years` varchar(255) NOT NULL COMMENT '建筑年代',
  `builded_at` datetime NOT NULL COMMENT '建筑日期',
  `live_in_at` datetime NOT NULL COMMENT '入住时间',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `building_base_id` (`building_base_id`),
  KEY `back_user_id` (`back_user_id`),
  CONSTRAINT `ah_house_ibfk_1` FOREIGN KEY (`back_user_id`) REFERENCES `ah_back_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ah_house_ibfk_2` FOREIGN KEY (`building_base_id`) REFERENCES `ah_building_base` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房源表';
