<?php

namespace app\home\controller;

use app\common\controller\HomeController;

/**
 * 默认控制器
 * @author Sir Fu
 */
class HandHouseController extends HomeController
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('nav','hand-house');
    }

    /**
     * 默认方法
     * @author Sir Fu
     */
    public function indexAction()
    {
        return view('hand_house/index',[
            'meta_title'=>'二手房',
        ]);
    }

}
