<?php

namespace app\home\controller;

use app\common\controller\HomeController;
use app\common\model\Slider;
use app\common\model\BuildingBase;
use app\common\model\House;
use app\common\model\News;

/**
 * 默认控制器
 * @author Sir Fu
 */
class HouseController extends HomeController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('nav','house');
    }

    /**
     * 默认方法
     * @author Sir Fu
     */
    public function indexAction()
    {$list = [];
        $where = ['type'=>'3'];
        $slider = Slider::getSlider($where);
        foreach ($slider as $item){
            $list[] = [
                'title'=>$item['title'],
                'desc'=>$item['description'],
                'target'=>$item['target'],
                'url'=>$item['url'],
            ];
        }
        if (empty($list)){
            $where = ['type'=>'1'];
            $slider = Slider::getSlider($where);
            foreach ($slider as $item){
                $list[] = [
                    'title'=>$item['title'],
                    'desc'=>$item['description'],
                    'target'=>$item['target'],
                    'url'=>$item['url'],
                ];
            }
        }
        if (empty($list)){
            $list[] = [
                'title'=>'',
                'desc'=>'',
                'target'=>'',
                'url'=>'/static/uploads/theme/new-house/theme-banner-new-house.jpg',
            ];
        }
        $slider = json_encode($list);

        //新房
        $houseModel = House::load();
        $house = $houseModel->where([])->select();

        // 资讯
        $newsModel = News::load();
        $news = $newsModel->where(['type'=>'2'])->select();

        return view('house/index',[
            'meta_title'=>'新房',
            'slider'=>$slider,
            'house'=>$house,
            'news'=>$news,
        ]);
    }

    /**
     * 默认方法
     * @author Sir Fu
     */
    public function buildAction()
    {
        return view('house/build',[
            'meta_title'=>'楼盘',
        ]);
    }

}
