<?php

namespace app\home\controller;

use app\common\controller\HomeController;
use app\common\model\Slider;

/**
 * 默认控制器
 * @author Sir Fu
 */
class NewsController extends HomeController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('nav','news');
    }
    /**
     * 默认方法
     * @author Sir Fu
     */
    public function indexAction()
    {
        return view('news/index',[
            'meta_title'=>'楼盘',
        ]);
    }

}
